# These are supported funding model platforms

github: #
patreon: rapidpunches
open_collective: #
ko_fi: rapidpunches
tidelift: # 
community_bridge: # 
liberapay: rapidpunches
issuehunt: # 
otechie: # 
custom: # 
